### ISSUE TITLE
TLSv* constants in client and server

### ISSUE THREAD

**Issue by Hywan** [hoaproject/Socket#22]
Since PHP5.6, we have new TLSv* constants (like ` 	STREAM_CRYPTO_METHOD_TLSv1_0_CLIENT`). We should implement them.

Who want to implement that? /cc @hoaproject/hoackers

**Comment by Hywan** [comment]
Ping @hoaproject/hoackers? Maybe @shulard?

**Comment by shulard** [comment]
I'll take a look during this week !

**Comment by Hywan** [comment]
Excellent!

**Comment by shulard** [comment]
Does this only mean adding new constants in the Hoa\Socket\Client object ? If that, the php.net doc must be udapted too: https://secure.php.net/manual/en/function.stream-socket-enable-crypto.php

**Comment by Hywan** [comment]
All new constants can be found here: http://php.net/manual/en/migration56.constants.php. Maybe `STREAM_CRYPTO_METHOD_ANY_CLIENT` and `STREAM_CRYPTO_METHOD_ANY_SERVER` can be useful for us but I don't know their respective meaning.

Yes, we should open a bug in php.net or edit the documentation directly: https://edit.php.net/?project=PHP.

**Comment by shulard** [comment]
Ok, I'll edit the doc :smile:
I've also added the `ANY` constants...
