### ISSUE TITLE
How should we pass a context to a Socket/Client ?

### ISSUE THREAD

**Issue by Oliboy50** [hoaproject/Socket#23]
The "context" assignment is commented in `&_open` method.

When I uncomment this, my connection just work as expected.

The relevant code: 
https://github.com/hoaproject/Socket/blob/master/Client.php#L155

What is the proper way of passing a socket context then?

**Comment by jubianchi** [comment]
I just blames the file and the commit in which those comments were introduced seems unrelated with a potentiel bug with context: 6830694ca7eae6a0630960c7c8af656f8d81e49c

Given the message "Try crypto" I assume this is some kind of experimentation and those comment are a simple mistake ;)

@Hywan ? If you want I can revert those commits and alsofix CS erros ;)

**Comment by Hywan** [comment]
Oh sh*t, this branch was not supposed to be pushed!

**Comment by Hywan** [comment]
Gonna fix that very very soon! Sorry :-(.

**Comment by Hywan** [comment]
Ok, my bot pushed it for me. Our tests did not fail though… strange. I am working on it.

**Comment by Hywan** [comment]
Ok no wait, I am confused. My branch is not pushed, that's another commit, hopefully :-p.

**Comment by Hywan** [comment]
@Oliboy50 0.15.07.20 has been released: https://github.com/hoaproject/Socket/releases/tag/0.15.07.20.

**Comment by Hywan** [comment]
And sorry for the delay, I was off :-/.
